[package]
name = "leanteach"
version = "0.1"
lean_version = "leanprover-community/lean:3.16.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "14292790529293a7ebc8caa70fc26b374e52a799"}
